### ISSUE TITLE
youtube-dl-exec这个包下载不了

### ISSUE THREAD

**Issue by Elias-cug** [Lanseria/video-downloader#1]

**Comment by Elias-cug** [comment]
ERR_PNPM_FETCH_404  GET https://codeload.github.com/Lanseria/yt-dlp-exec/tar.gz/43876c60e67617b1ca2b2a0fba470bca8d47dffb: Not Found - 404

**Comment by lanseria** [comment]
> ERR_PNPM_FETCH_404  GET https://codeload.github.com/Lanseria/yt-dlp-exec/tar.gz/43876c60e67617b1ca2b2a0fba470bca8d47dffb: Not Found - 404

你是开发还是生产？我晚上回去看

**Comment by Elias-cug** [comment]
> > ERR_PNPM_FETCH_404  GET https://codeload.github.com/Lanseria/yt-dlp-exec/tar.gz/43876c60e67617b1ca2b2a0fba470bca8d47dffb: Not Found - 404
> 
> 你是开发还是生产？我晚上回去看
开发，最近要做一个下载器，b站看到你视频又找到了github，下包的时候有个链接404

**Comment by lanseria** [comment]
> > > ERR_PNPM_FETCH_404  GET https://codeload.github.com/Lanseria/yt-dlp-exec/tar.gz/43876c60e67617b1ca2b2a0fba470bca8d47dffb: Not Found - 404
> > 
> > 
> > 你是开发还是生产？我晚上回去看
> > 开发，最近要做一个下载器，b站看到你视频又找到了github，下包的时候有个链接404

重新pull看看。改了名字
